kafka-kraft-on-k8s:
#  namespace: kafka
  replicaCount: 1
  kraft:
    enabled: true
  zookeeper:
    enabled: false
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  service:
    type: ClusterIP
  listeners:
    plaintext:
      enabled: true
      port: 9092
    controller:
      enabled: true
      replicas: 1
      port: 9093
  metrics:
    enabled: false
